// src/TransBrain.VueWeb/src/views/DriverList.vue
<script setup lang="ts">
import axios from 'axios';
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { deleteDriver, listDrivers, type Driver } from '../api/drivers';
import { useAuthStore } from '../stores/auth';

/**
 * The API's maximum page size. Neither frontend has pagination controls yet, so whatever one
 * request returns is all a user can ever see - and lists come back sorted ascending, meaning a
 * default page of 20 shows the twenty OLDEST records and hides everything added since. Asking
 * for the cap is a stopgap, not a fix: real paging controls are still needed above 100 rows.
 */
const LIST_PAGE_SIZE = 100;

const auth = useAuthStore();
const router = useRouter();
const drivers = ref<Driver[]>([]);
const errorMessage = ref<string | null>(null);
// Separate from errorMessage: a failed delete must not hide the table the way a failed list
// load does (mirrors VehicleList.vue's actionError - see that file for why).
const actionError = ref<string | null>(null);

const headers = [
    { title: 'Last name', key: 'lastName' },
    { title: 'First name', key: 'firstName' },
    { title: 'License classes', key: 'licenseClasses' },
    { title: 'Status', key: 'status' },
    { title: 'Actions', key: 'actions', sortable: false },
];

onMounted(async () => {
    if (auth.isAuthenticated) {
        await refresh();
    }
});

async function refresh(): Promise<void> {
    try {
        drivers.value = (await listDrivers(LIST_PAGE_SIZE)).items;
    } catch (error) {
        errorMessage.value = describe(error, 'The driver list could not be loaded.');
    }
}

// See VehicleList.vue's delete for why this action is shown to every authenticated user rather
// than hidden by role: this SPA has no role-decoding infrastructure yet, and a non-admin gets a
// clear 403-driven message here instead of a hidden button.
async function remove(driver: Driver): Promise<void> {
    actionError.value = null;
    try {
        await deleteDriver(driver.id);
        await refresh();
    } catch (error) {
        // A policy failure (e.g. a non-admin's 403) is rejected by ASP.NET's authorization
        // middleware before the endpoint runs, so it carries no ProblemDetails body at all -
        // the fallback text is therefore action-specific, not the list-load one.
        actionError.value = describe(error, 'The driver could not be deleted.');
    }
}

// ProblemDetails' `errors` dictionary is now keyed by field name (Task 1 of the
// 2026-08-29 master-data-completion phase fixed the previous error-code keying), but this
// component has no form fields to bind those keys onto - it only ever needs the free-text
// summary, which `title`/`detail` already provide.
function describe(error: unknown, fallback: string): string {
    if (axios.isAxiosError(error)) {
        const problem = error.response?.data as { title?: string; detail?: string } | undefined;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.response?.status ?? 'unknown'})`;
    }
    return fallback;
}
</script>

<template>
    <v-container>
        <template v-if="auth.isAuthenticated">
            <h1>Drivers</h1>
            <v-btn
                v-if="auth.can('masterData.write')"
                data-testid="driver-add"
                @click="router.push('/drivers/new')"
                >Add driver</v-btn
            >
            <p v-if="actionError" data-testid="driver-action-error">{{ actionError }}</p>
            <p v-if="errorMessage" data-testid="driver-list-error">{{ errorMessage }}</p>
            <!-- items-per-page="-1": the API already returned one page, and Vuetify would
                 paginate that page AGAIN at ten rows, so a record the server did return could
                 still be invisible. One pagination - the server's - is enough, and it is what
                 the Angular app does. -->
            <v-data-table
                v-else
                :headers="headers"
                :items="drivers"
                :items-per-page="-1"
                item-value="id"
                data-testid="driver-table"
            >
                <template #item.lastName="{ item }">
                    <span data-testid="driver-lastname">{{ item.lastName }}</span>
                </template>
                <template #item.firstName="{ item }">
                    <span data-testid="driver-firstname">{{ item.firstName }}</span>
                </template>
                <template #item.licenseClasses="{ item }">
                    {{ item.licenseClasses.join(', ') }}
                </template>
                <template #item.actions="{ item }">
                    <template v-if="auth.can('masterData.write')">
                        <v-btn data-testid="driver-edit" @click="router.push(`/drivers/${item.id}`)">Edit</v-btn>
                        <v-btn data-testid="driver-delete" @click="remove(item)">Delete</v-btn>
                    </template>
                </template>
            </v-data-table>
        </template>
        <p v-else>Please sign in to see the drivers.</p>
    </v-container>
</template>

// src/TransBrain.Web/src/app/drivers/driver-list.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { MatTableModule } from '@angular/material/table';
import { MatButtonModule } from '@angular/material/button';
import { RouterLink } from '@angular/router';
import { SessionService } from '../auth/session.service';
import { Driver, DriverService } from './driver.service';

/**
 * The API's maximum page size. Neither frontend has pagination controls yet, so whatever one
 * request returns is all a user can ever see - and lists come back sorted ascending, meaning a
 * default page of 20 shows the twenty OLDEST records and hides everything added since. Asking
 * for the cap is a stopgap, not a fix: real paging controls are still needed above 100 rows.
 */
const LIST_PAGE_SIZE = 100;

@Component({
    selector: 'app-driver-list',
    standalone: true,
    imports: [MatTableModule, MatButtonModule, RouterLink],
    template: `
        @if (session.isAuthenticated()) {
            <h1>Drivers</h1>
            @if (session.can('masterData.write')) {
                <a mat-raised-button routerLink="/drivers/new" data-testid="driver-add">Add driver</a>
            }
            @if (actionError(); as message) {
                <p data-testid="driver-action-error">{{ message }}</p>
            }
            @if (errorMessage(); as message) {
                <p data-testid="driver-list-error">{{ message }}</p>
            } @else {
                <table mat-table [dataSource]="drivers()">
                    <ng-container matColumnDef="lastName">
                        <th mat-header-cell *matHeaderCellDef>Last name</th>
                        <td mat-cell *matCellDef="let d" data-testid="driver-lastname">{{ d.lastName }}</td>
                    </ng-container>
                    <ng-container matColumnDef="firstName">
                        <th mat-header-cell *matHeaderCellDef>First name</th>
                        <td mat-cell *matCellDef="let d" data-testid="driver-firstname">{{ d.firstName }}</td>
                    </ng-container>
                    <ng-container matColumnDef="licenseClasses">
                        <th mat-header-cell *matHeaderCellDef>License classes</th>
                        <td mat-cell *matCellDef="let d">{{ d.licenseClasses.join(', ') }}</td>
                    </ng-container>
                    <ng-container matColumnDef="status">
                        <th mat-header-cell *matHeaderCellDef>Status</th>
                        <td mat-cell *matCellDef="let d">{{ d.status }}</td>
                    </ng-container>
                    <ng-container matColumnDef="actions">
                        <th mat-header-cell *matHeaderCellDef>Actions</th>
                        <td mat-cell *matCellDef="let d">
                            <a mat-button [routerLink]="['/drivers', d.id]" data-testid="driver-edit">Edit</a>
                            <button mat-button data-testid="driver-delete" (click)="delete(d)">Delete</button>
                        </td>
                    </ng-container>
                    <tr mat-header-row *matHeaderRowDef="columns"></tr>
                    <tr mat-row *matRowDef="let row; columns: columns"></tr>
                </table>
            }
        } @else {
            <p>Please sign in to see the drivers.</p>
        }
    `,
})
export class DriverListComponent {
    private readonly service = inject(DriverService);
    protected readonly session = inject(SessionService);

    protected readonly columns = ['lastName', 'firstName', 'licenseClasses', 'status', 'actions'];
    protected readonly drivers = signal<Driver[]>([]);
    protected readonly errorMessage = signal<string | null>(null);
    // Separate from errorMessage: a failed delete must not hide the table the way a failed
    // list load does (mirrors VehicleListComponent's actionError - see that file for why).
    protected readonly actionError = signal<string | null>(null);

    constructor() {
        this.session.ready.subscribe((isAuthenticated) => {
            if (isAuthenticated) {
                this.refresh();
            }
        });
    }

    // See VehicleListComponent.delete for why these actions are shown to every authenticated
    // user rather than hidden by role: this SPA has no role-decoding infrastructure yet, and a
    // non-admin gets a clear 403-driven message here instead of a hidden button.
    protected delete(driver: Driver): void {
        this.actionError.set(null);
        this.service.remove(driver.id).subscribe({
            next: () => this.refresh(),
            // A policy failure (e.g. a non-admin's 403) is rejected by ASP.NET's authorization
            // middleware before the endpoint runs, so it carries no ProblemDetails body at all -
            // describe()'s fallback text is therefore action-specific, not the list-load one.
            error: (error: HttpErrorResponse) =>
                this.actionError.set(this.describe(error, 'The driver could not be deleted.')),
        });
    }

    private refresh(): void {
        this.service.list(LIST_PAGE_SIZE).subscribe({
            next: (page) => this.drivers.set(page.items),
            error: (error: HttpErrorResponse) =>
                this.errorMessage.set(this.describe(error, 'The driver list could not be loaded.')),
        });
    }

    // See VehicleListComponent.describe: same reasoning, same now-superseded Phase 1 history.
    private describe(error: HttpErrorResponse, fallback: string): string {
        const problem = error.error as { title?: string; detail?: string } | null;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.status})`;
    }
}
