// src/TransBrain.Web/src/app/orders/order-list.component.ts
import { DatePipe } from '@angular/common';
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatTableModule } from '@angular/material/table';
import { RouterLink } from '@angular/router';
import { SessionService } from '../auth/session.service';
import { Order, OrderService } from './order.service';

/**
 * The API's maximum page size. Neither frontend has pagination controls yet, so whatever one
 * request returns is all a user can ever see - and lists come back sorted ascending, meaning a
 * default page of 20 shows the twenty OLDEST records and hides everything added since. Asking
 * for the cap is a stopgap, not a fix: real paging controls are still needed above 100 rows.
 */
const LIST_PAGE_SIZE = 100;

@Component({
    selector: 'app-order-list',
    standalone: true,
    imports: [MatTableModule, MatButtonModule, MatFormFieldModule, MatSelectModule, RouterLink, DatePipe],
    template: `
        @if (session.isAuthenticated()) {
            <h1>Orders</h1>
            @if (session.can('dispatch.write')) {
                <a mat-raised-button routerLink="/orders/new" data-testid="order-add">Add order</a>
            }
            <mat-form-field>
                <mat-label>Status</mat-label>
                <mat-select
                    [value]="statusFilter()"
                    (valueChange)="filterByStatus($event)"
                    data-testid="order-status-filter"
                >
                    <mat-option [value]="''">All</mat-option>
                    @for (status of statusOptions; track status) {
                        <mat-option [value]="status">{{ status }}</mat-option>
                    }
                </mat-select>
            </mat-form-field>
            @if (actionError(); as message) {
                <p data-testid="order-action-error">{{ message }}</p>
            }
            @if (errorMessage(); as message) {
                <p data-testid="order-list-error">{{ message }}</p>
            } @else {
                <table mat-table [dataSource]="orders()">
                    <ng-container matColumnDef="orderNumber">
                        <th mat-header-cell *matHeaderCellDef>Order number</th>
                        <td mat-cell *matCellDef="let o" data-testid="order-number">{{ o.orderNumber }}</td>
                    </ng-container>
                    <ng-container matColumnDef="consignor">
                        <th mat-header-cell *matHeaderCellDef>Consignor</th>
                        <td mat-cell *matCellDef="let o" data-testid="order-consignor">{{ o.consignor.name }}</td>
                    </ng-container>
                    <ng-container matColumnDef="consignee">
                        <th mat-header-cell *matHeaderCellDef>Consignee</th>
                        <td mat-cell *matCellDef="let o" data-testid="order-consignee">{{ o.consignee.name }}</td>
                    </ng-container>
                    <ng-container matColumnDef="cargo">
                        <th mat-header-cell *matHeaderCellDef>Cargo</th>
                        <td mat-cell *matCellDef="let o" data-testid="order-cargo">{{ o.cargoDescription }}</td>
                    </ng-container>
                    <ng-container matColumnDef="pickup">
                        <th mat-header-cell *matHeaderCellDef>Pickup</th>
                        <td mat-cell *matCellDef="let o">{{ o.pickupFrom | date: 'short' }}</td>
                    </ng-container>
                    <ng-container matColumnDef="status">
                        <th mat-header-cell *matHeaderCellDef>Status</th>
                        <td mat-cell *matCellDef="let o" data-testid="order-status">{{ o.status }}</td>
                    </ng-container>
                    <ng-container matColumnDef="actions">
                        <th mat-header-cell *matHeaderCellDef>Actions</th>
                        <td mat-cell *matCellDef="let o">
                            <a mat-button [routerLink]="['/orders', o.id]" data-testid="order-edit">Edit</a>
                            @if (pendingCancelId() === o.id) {
                                <!-- Inline confirmation rather than window.confirm(): a native
                                     dialog blocks until a Playwright dialog handler answers it,
                                     and an in-DOM confirmation is what the e2e spec can assert. -->
                                <button mat-button data-testid="order-cancel-confirm" (click)="cancel(o)">
                                    Confirm cancel
                                </button>
                                <button mat-button data-testid="order-cancel-abort" (click)="abortCancel()">
                                    Keep order
                                </button>
                            } @else {
                                <button mat-button data-testid="order-cancel" (click)="askToCancel(o)">
                                    Cancel order
                                </button>
                            }
                        </td>
                    </ng-container>
                    <tr mat-header-row *matHeaderRowDef="columns"></tr>
                    <tr mat-row *matRowDef="let row; columns: columns"></tr>
                </table>
            }
        } @else {
            <p>Please sign in to see the orders.</p>
        }
    `,
})
export class OrderListComponent {
    private readonly service = inject(OrderService);
    protected readonly session = inject(SessionService);

    protected readonly columns = [
        'orderNumber',
        'consignor',
        'consignee',
        'cargo',
        'pickup',
        'status',
        'actions',
    ];
    protected readonly statusOptions = ['Draft', 'Planned', 'InTransit', 'Delivered', 'Cancelled'];
    protected readonly orders = signal<Order[]>([]);
    protected readonly errorMessage = signal<string | null>(null);
    // Separate from errorMessage: a failed cancel must not hide the table the way a failed
    // list load does (mirrors DriverListComponent's actionError).
    protected readonly actionError = signal<string | null>(null);
    protected readonly statusFilter = signal('');
    protected readonly pendingCancelId = signal<string | null>(null);

    constructor() {
        this.session.ready.subscribe((isAuthenticated) => {
            if (isAuthenticated) {
                this.refresh();
            }
        });
    }

    protected filterByStatus(status: string): void {
        this.statusFilter.set(status);
        this.pendingCancelId.set(null);
        this.refresh();
    }

    protected askToCancel(order: Order): void {
        this.actionError.set(null);
        this.pendingCancelId.set(order.id);
    }

    protected abortCancel(): void {
        this.pendingCancelId.set(null);
    }

    // Shown for every order rather than hidden for the ones the domain will refuse: an order
    // already in transit answers 409 with a message explaining why, which is more useful than
    // a button that silently is not there. Same reasoning as the master-data delete actions,
    // which are shown to every authenticated user rather than hidden by role.
    protected cancel(order: Order): void {
        this.actionError.set(null);
        this.pendingCancelId.set(null);
        this.service.cancel(order.id).subscribe({
            next: () => this.refresh(),
            // A policy failure (e.g. a viewer's 403) is rejected by ASP.NET's authorization
            // middleware before the endpoint runs, so it carries no ProblemDetails body at all -
            // describe()'s fallback text is therefore action-specific, not the list-load one.
            error: (error: HttpErrorResponse) =>
                this.actionError.set(this.describe(error, 'The order could not be cancelled.')),
        });
    }

    private refresh(): void {
        this.service.list(this.statusFilter(), LIST_PAGE_SIZE).subscribe({
            next: (page) => this.orders.set(page.items),
            error: (error: HttpErrorResponse) =>
                this.errorMessage.set(this.describe(error, 'The order list could not be loaded.')),
        });
    }

    // See DriverListComponent.describe: same reasoning, same now-superseded Phase 1 history.
    private describe(error: HttpErrorResponse, fallback: string): string {
        const problem = error.error as { title?: string; detail?: string } | null;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.status})`;
    }
}

// src/TransBrain.VueWeb/src/views/OrderList.vue
<script setup lang="ts">
import axios from 'axios';
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { cancelOrder, listOrders, type Order } from '../api/orders';
import { useAuthStore } from '../stores/auth';

/**
 * The API's maximum page size. Neither frontend has pagination controls yet, so whatever one
 * request returns is all a user can ever see - and lists come back sorted ascending, meaning a
 * default page of 20 shows the twenty OLDEST records and hides everything added since. Asking
 * for the cap is a stopgap, not a fix: real paging controls are still needed above 100 rows.
 */
const LIST_PAGE_SIZE = 100;

const auth = useAuthStore();
const router = useRouter();
const orders = ref<Order[]>([]);
const errorMessage = ref<string | null>(null);
// Separate from errorMessage: a failed cancel must not hide the table the way a failed list
// load does (mirrors DriverList.vue's actionError).
const actionError = ref<string | null>(null);
const statusFilter = ref('');
const pendingCancelId = ref<string | null>(null);

const statusOptions = ['Draft', 'Planned', 'InTransit', 'Delivered', 'Cancelled'];

const headers = [
    { title: 'Order number', key: 'orderNumber' },
    { title: 'Consignor', key: 'consignor' },
    { title: 'Consignee', key: 'consignee' },
    { title: 'Cargo', key: 'cargoDescription' },
    { title: 'Pickup', key: 'pickupFrom' },
    { title: 'Status', key: 'status' },
    { title: 'Actions', key: 'actions', sortable: false },
];

onMounted(async () => {
    if (auth.isAuthenticated) {
        await refresh();
    }
});

async function refresh(): Promise<void> {
    try {
        orders.value = (await listOrders(statusFilter.value, LIST_PAGE_SIZE)).items;
    } catch (error) {
        errorMessage.value = describe(error, 'The order list could not be loaded.');
    }
}

async function filterByStatus(status: string): Promise<void> {
    statusFilter.value = status;
    pendingCancelId.value = null;
    await refresh();
}

function askToCancel(order: Order): void {
    actionError.value = null;
    pendingCancelId.value = order.id;
}

function abortCancel(): void {
    pendingCancelId.value = null;
}

// Shown for every order rather than hidden for the ones the domain will refuse: an order
// already in transit answers 409 with a message explaining why, which is more useful than a
// button that silently is not there. Same reasoning as the master-data delete actions.
async function cancel(order: Order): Promise<void> {
    actionError.value = null;
    pendingCancelId.value = null;
    try {
        await cancelOrder(order.id);
        await refresh();
    } catch (error) {
        // A policy failure (e.g. a viewer's 403) is rejected by ASP.NET's authorization
        // middleware before the endpoint runs, so it carries no ProblemDetails body at all -
        // the fallback text is therefore action-specific, not the list-load one.
        actionError.value = describe(error, 'The order could not be cancelled.');
    }
}

function formatInstant(iso: string): string {
    return new Date(iso).toLocaleString();
}

// ProblemDetails' `errors` dictionary is now keyed by field name, but this component has no
// form fields to bind those keys onto - it only ever needs the free-text summary, which
// `title`/`detail` already provide.
function describe(error: unknown, fallback: string): string {
    if (axios.isAxiosError(error)) {
        const problem = error.response?.data as { title?: string; detail?: string } | undefined;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.response?.status ?? 'unknown'})`;
    }
    return fallback;
}
</script>

<template>
    <v-container>
        <template v-if="auth.isAuthenticated">
            <h1>Orders</h1>
            <v-btn
                v-if="auth.can('dispatch.write')"
                data-testid="order-add"
                @click="router.push('/orders/new')"
                >Add order</v-btn
            >
            <!-- A plain <select>, not <v-select>: Vuetify's select renders an overlay listbox
                 rather than native options, and the same testid-lands-on-a-wrapper-div problem
                 DriverForm.vue documents for v-text-field applies to it. -->
            <div>
                <label for="order-status-filter">Status</label>
                <select
                    id="order-status-filter"
                    data-testid="order-status-filter"
                    :value="statusFilter"
                    @change="filterByStatus(($event.target as HTMLSelectElement).value)"
                >
                    <option value="">All</option>
                    <option v-for="status in statusOptions" :key="status" :value="status">{{ status }}</option>
                </select>
            </div>
            <p v-if="actionError" data-testid="order-action-error">{{ actionError }}</p>
            <p v-if="errorMessage" data-testid="order-list-error">{{ errorMessage }}</p>
            <!-- items-per-page="-1": the API already returned one page, and Vuetify would
                 paginate that page AGAIN at ten rows, so a record the server did return could
                 still be invisible. One pagination - the server's - is enough, and it is what
                 the Angular app does. -->
            <v-data-table
                v-else
                :headers="headers"
                :items="orders"
                :items-per-page="-1"
                item-value="id"
                data-testid="order-table"
            >
                <template #item.orderNumber="{ item }">
                    <span data-testid="order-number">{{ item.orderNumber }}</span>
                </template>
                <template #item.consignor="{ item }">
                    <span data-testid="order-consignor">{{ item.consignor.name }}</span>
                </template>
                <template #item.consignee="{ item }">
                    <span data-testid="order-consignee">{{ item.consignee.name }}</span>
                </template>
                <template #item.cargoDescription="{ item }">
                    <span data-testid="order-cargo">{{ item.cargoDescription }}</span>
                </template>
                <template #item.pickupFrom="{ item }">
                    {{ formatInstant(item.pickupFrom) }}
                </template>
                <template #item.status="{ item }">
                    <span data-testid="order-status">{{ item.status }}</span>
                </template>
                <template #item.actions="{ item }">
                    <template v-if="auth.can('dispatch.write')">
                    <v-btn data-testid="order-edit" @click="router.push(`/orders/${item.id}`)">Edit</v-btn>
                    <!-- Inline confirmation rather than window.confirm(): a native dialog blocks
                         until a Playwright dialog handler answers it, and an in-DOM confirmation
                         is what the e2e spec can assert. Mirrors the Angular list. -->
                    <template v-if="pendingCancelId === item.id">
                        <v-btn data-testid="order-cancel-confirm" @click="cancel(item)">Confirm cancel</v-btn>
                        <v-btn data-testid="order-cancel-abort" @click="abortCancel()">Keep order</v-btn>
                    </template>
                    <v-btn v-else data-testid="order-cancel" @click="askToCancel(item)">Cancel order</v-btn>
                    </template>
                </template>
            </v-data-table>
        </template>
        <p v-else>Please sign in to see the orders.</p>
    </v-container>
</template>
