// src/TransBrain.Web/src/app/tours/tour-form.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, ValidationErrors, Validators } from '@angular/forms';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatInputModule } from '@angular/material/input';
import { MatSelectModule } from '@angular/material/select';
import { Router } from '@angular/router';
import { SessionService } from '../auth/session.service';
import {switchMap} from 'rxjs';
import { Driver, DriverService } from '../drivers/driver.service';
import { Vehicle, VehicleService } from '../vehicles/vehicle.service';
import { TourService } from './tour.service';

/** The API's maximum page size. A picker must offer every choice, not the first twenty. */
const PICKER_PAGE_SIZE = 100;

interface ProblemDetailsBody {
    errors?: Record<string, string[]>;
    detail?: string;
    title?: string;
    errorCode?: string;
}

@Component({
    selector: 'app-tour-form',
    standalone: true,
    imports: [ReactiveFormsModule, MatButtonModule, MatFormFieldModule, MatInputModule, MatSelectModule],
    template: `
        <h1>New tour</h1>
        @if (formError(); as message) {
            <p data-testid="tour-form-error">{{ message }}</p>
        }
        <form [formGroup]="form" (ngSubmit)="save()">
            <mat-form-field>
                <mat-label>Tour date</mat-label>
                <input matInput type="date" formControlName="tourDate" data-testid="tour-tourDate" />
                @if (form.controls.tourDate.errors; as errors) {
                    <mat-error data-testid="tour-tourDate-error">{{ fieldErrorText(errors) }}</mat-error>
                }
            </mat-form-field>
            <mat-form-field>
                <mat-label>Vehicle</mat-label>
                <mat-select formControlName="vehicleId" data-testid="tour-vehicleId">
                    @for (vehicle of vehicles(); track vehicle.id) {
                        <mat-option [value]="vehicle.id">{{ vehicle.licensePlate }}</mat-option>
                    }
                </mat-select>
                @if (form.controls.vehicleId.errors; as errors) {
                    <mat-error data-testid="tour-vehicleId-error">{{ fieldErrorText(errors) }}</mat-error>
                }
            </mat-form-field>
            <mat-form-field>
                <mat-label>Driver</mat-label>
                <mat-select formControlName="driverId" data-testid="tour-driverId">
                    @for (driver of drivers(); track driver.id) {
                        <mat-option [value]="driver.id">{{ driver.lastName }}, {{ driver.firstName }}</mat-option>
                    }
                </mat-select>
                @if (form.controls.driverId.errors; as errors) {
                    <mat-error data-testid="tour-driverId-error">{{ fieldErrorText(errors) }}</mat-error>
                }
            </mat-form-field>
            <button mat-raised-button type="submit" data-testid="tour-save">Save</button>
            <button mat-button type="button" data-testid="tour-cancel" (click)="cancel()">Cancel</button>
        </form>
    `,
})
export class TourFormComponent {
    private readonly service = inject(TourService);
    private readonly vehicleService = inject(VehicleService);
    private readonly driverService = inject(DriverService);
    private readonly router = inject(Router);
    private readonly fb = inject(FormBuilder);
    // SessionService.ready is what guarantees angular-auth-oidc-client has rehydrated its
    // stored session before the first request goes out. A form reached by a DIRECT navigation -
    // a bookmark, a page reload while editing, browser back - has no list component in its
    // lifetime, so without this every request from it answered 401 to a plainly signed-in user.
    // The one checkAuth() behind it runs in the App component.
    protected readonly session = inject(SessionService);

    protected readonly vehicles = signal<Vehicle[]>([]);
    protected readonly drivers = signal<Driver[]>([]);
    protected readonly formError = signal<string | null>(null);

    protected readonly form = this.fb.nonNullable.group({
        tourDate: ['', Validators.required],
        vehicleId: ['', Validators.required],
        driverId: ['', Validators.required],
    });

    constructor() {
        this.session.ready.pipe(switchMap(() => this.vehicleService.list(PICKER_PAGE_SIZE))).subscribe({
            next: (page) => this.vehicles.set(page.items),
            error: (error: HttpErrorResponse) =>
                this.formError.set(this.describeFailure(error, 'The vehicle list could not be loaded.')),
        });

        this.session.ready.pipe(switchMap(() => this.driverService.list(PICKER_PAGE_SIZE))).subscribe({
            next: (page) => this.drivers.set(page.items),
            error: (error: HttpErrorResponse) =>
                this.formError.set(this.describeFailure(error, 'The driver list could not be loaded.')),
        });
    }

    // See DriverFormComponent.fieldErrorText for the full reasoning.
    protected fieldErrorText(errors: ValidationErrors): string {
        if (errors['server']) {
            return errors['server'] as string;
        }
        if (errors['required']) {
            return 'This field is required.';
        }
        return 'This field is invalid.';
    }

    protected save(): void {
        this.formError.set(null);
        if (this.form.invalid) {
            this.form.markAllAsTouched();
            return;
        }

        this.session.ready
            .pipe(switchMap(() => this.service.create(this.form.getRawValue())))
            .subscribe({
                // To the detail page, not the list: a dispatcher's next action after planning a
                // tour is always to put orders on it.
                next: (tour) => this.router.navigateByUrl(`/tours/${tour.id}`),
                error: (error: HttpErrorResponse) => this.applyServerErrors(error),
            });
    }

    protected cancel(): void {
        this.router.navigateByUrl('/tours');
    }

    // See OrderFormComponent.applyServerErrors: binding the field-keyed `errors` dictionary is
    // correct and supersedes a Phase 1 instruction that forbade it.
    private applyServerErrors(error: HttpErrorResponse): void {
        const problem = error.error as ProblemDetailsBody | null;

        if (problem?.errors) {
            for (const [field, messages] of Object.entries(problem.errors)) {
                const path = field
                    .split('.')
                    .map((segment) => segment.charAt(0).toLowerCase() + segment.slice(1))
                    .join('.');
                const control = this.form.get(path);
                const message = messages.join(' ');
                if (control) {
                    control.setErrors({ server: message });
                    control.markAsTouched();
                } else {
                    this.formError.update((existing) => (existing ? `${existing} ${message}` : message));
                }
            }
            return;
        }

        // A double booking, an unavailable vehicle and an expired licence all arrive here as a
        // 409 with a detail message naming the reason - which is exactly what the dispatcher
        // needs to see, so it is shown verbatim rather than replaced with a generic sentence.
        this.formError.set(this.describeFailure(error, 'The tour could not be saved.'));
    }

    private describeFailure(error: HttpErrorResponse, fallback: string): string {
        const problem = error.error as ProblemDetailsBody | null;
        const message = problem?.detail ?? problem?.title ?? fallback;
        return `${message} (HTTP ${error.status})`;
    }
}

// src/TransBrain.VueWeb/src/views/TourForm.vue
<script setup lang="ts">
import axios from 'axios';
import { onMounted, reactive, ref } from 'vue';
import { useRouter } from 'vue-router';
import { listDrivers, type Driver } from '../api/drivers';
import { createTour } from '../api/tours';
import { listVehicles, type Vehicle } from '../api/vehicles';

interface ProblemDetailsBody {
    errors?: Record<string, string[]>;
    detail?: string;
    title?: string;
    errorCode?: string;
}

/** The API's maximum page size. A picker must offer every choice, not the first twenty. */
const PICKER_PAGE_SIZE = 100;

const router = useRouter();

const vehicles = ref<Vehicle[]>([]);
const drivers = ref<Driver[]>([]);

const form = reactive({
    tourDate: '',
    vehicleId: '',
    driverId: '',
});

const fieldErrors = reactive<Record<string, string | null>>({
    tourDate: null,
    vehicleId: null,
    driverId: null,
});

// Gates field error rendering the same way Angular Material's default ErrorStateMatcher does
// (invalid && (touched || submitted)) - a fresh form must not show "This field is required"
// before the user has done anything.
const attemptedSubmit = ref(false);
const formError = ref<string | null>(null);

onMounted(async () => {
    try {
        vehicles.value = (await listVehicles(PICKER_PAGE_SIZE)).items;
        drivers.value = (await listDrivers(PICKER_PAGE_SIZE)).items;
    } catch (error) {
        // A failed load is not a failed save - give it its own wording.
        formError.value = describeFailure(error, 'The vehicles and drivers could not be loaded.');
    }
});

function validateRequired(): boolean {
    fieldErrors.tourDate = form.tourDate ? null : 'This field is required.';
    fieldErrors.vehicleId = form.vehicleId ? null : 'This field is required.';
    fieldErrors.driverId = form.driverId ? null : 'This field is required.';
    return Object.values(fieldErrors).every((message) => message === null);
}

async function save(): Promise<void> {
    formError.value = null;
    attemptedSubmit.value = true;
    if (!validateRequired()) {
        return;
    }

    try {
        const tour = await createTour({ ...form });
        // To the detail page, not the list: a dispatcher's next action after planning a tour is
        // always to put orders on it.
        await router.push(`/tours/${tour.id}`);
    } catch (error) {
        applyServerErrors(error);
    }
}

function cancel(): void {
    router.push('/tours');
}

function applyServerErrors(error: unknown): void {
    if (axios.isAxiosError(error)) {
        const problem = error.response?.data as ProblemDetailsBody | undefined;

        if (problem?.errors) {
            for (const [field, messages] of Object.entries(problem.errors)) {
                const fieldName = field.charAt(0).toLowerCase() + field.slice(1);
                const message = messages.join(' ');
                if (fieldName in fieldErrors) {
                    fieldErrors[fieldName] = message;
                    attemptedSubmit.value = true;
                } else {
                    formError.value = formError.value ? `${formError.value} ${message}` : message;
                }
            }
            return;
        }

        // A double booking, a vehicle in the workshop and an expired licence all arrive here as
        // a 409 whose detail names the reason - exactly what the dispatcher needs, so it is
        // shown verbatim rather than replaced by a generic sentence.
        formError.value = describeFailure(error, 'The tour could not be saved.');
        return;
    }

    formError.value = 'The tour could not be saved.';
}

function describeFailure(error: unknown, fallback: string): string {
    if (axios.isAxiosError(error)) {
        const problem = error.response?.data as ProblemDetailsBody | undefined;
        const message = problem?.detail ?? problem?.title ?? fallback;
        return `${message} (HTTP ${error.response?.status ?? 'unknown'})`;
    }
    return fallback;
}
</script>

<template>
    <v-container>
        <h1>New tour</h1>
        <p v-if="formError" data-testid="tour-form-error">{{ formError }}</p>
        <!-- novalidate: see VehicleForm.vue - without it a native input constraint can silently
             block the submit event before this handler ever runs. -->
        <form novalidate @submit.prevent="save">
            <div>
                <label for="tour-tourDate">Tour date</label>
                <input id="tour-tourDate" v-model="form.tourDate" type="date" data-testid="tour-tourDate" />
            </div>
            <p v-if="attemptedSubmit && fieldErrors.tourDate" data-testid="tour-tourDate-error">
                {{ fieldErrors.tourDate }}
            </p>

            <div>
                <label for="tour-vehicleId">Vehicle</label>
                <select id="tour-vehicleId" v-model="form.vehicleId" data-testid="tour-vehicleId">
                    <option value="">-</option>
                    <option v-for="vehicle in vehicles" :key="vehicle.id" :value="vehicle.id">
                        {{ vehicle.licensePlate }}
                    </option>
                </select>
            </div>
            <p v-if="attemptedSubmit && fieldErrors.vehicleId" data-testid="tour-vehicleId-error">
                {{ fieldErrors.vehicleId }}
            </p>

            <div>
                <label for="tour-driverId">Driver</label>
                <select id="tour-driverId" v-model="form.driverId" data-testid="tour-driverId">
                    <option value="">-</option>
                    <option v-for="driver in drivers" :key="driver.id" :value="driver.id">
                        {{ driver.lastName }}, {{ driver.firstName }}
                    </option>
                </select>
            </div>
            <p v-if="attemptedSubmit && fieldErrors.driverId" data-testid="tour-driverId-error">
                {{ fieldErrors.driverId }}
            </p>

            <v-btn type="submit" data-testid="tour-save">Save</v-btn>
            <v-btn type="button" data-testid="tour-cancel" @click="cancel">Cancel</v-btn>
        </form>
    </v-container>
</template>
