// src/TransBrain.Web/src/app/tours/tour-detail.component.ts
import { HttpErrorResponse } from '@angular/common/http';
import { Component, computed, inject, signal } from '@angular/core';
import { MatButtonModule } from '@angular/material/button';
import { MatFormFieldModule } from '@angular/material/form-field';
import { MatSelectModule } from '@angular/material/select';
import { MatTableModule } from '@angular/material/table';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { SessionService } from '../auth/session.service';
import { Observable, of, switchMap } from 'rxjs';
import { Order, OrderService } from '../orders/order.service';
import { Tour, TourService } from './tour.service';

@Component({
    selector: 'app-tour-detail',
    standalone: true,
    imports: [MatTableModule, MatButtonModule, MatFormFieldModule, MatSelectModule, RouterLink],
    template: `
        <h1>Tour</h1>
        @if (loadError(); as message) {
            <p data-testid="tour-detail-error">{{ message }}</p>
        }
        @if (tour(); as t) {
            <!-- tour-detail-* rather than tour-*: the list uses tour-status/tour-date/etc on its
                 cells, and a page-wide locator that matched both screens would be ambiguous the
                 moment a test navigated between them. -->
            <dl>
                <dt>Date</dt>
                <dd data-testid="tour-detail-date">{{ t.tourDate }}</dd>
                <dt>Vehicle</dt>
                <dd data-testid="tour-detail-vehicle">{{ t.vehicleLicensePlate }}</dd>
                <dt>Driver</dt>
                <dd data-testid="tour-detail-driver">{{ t.driverName }}</dd>
                <dt>Status</dt>
                <dd data-testid="tour-detail-status">{{ t.status }}</dd>
            </dl>

            <!-- The headroom a dispatcher needs before choosing the next order. The API already
                 sends both numbers, so showing them costs nothing extra. -->
            <section>
                <h2>Capacity</h2>
                <p data-testid="tour-capacity-weight">{{ t.totalWeightKg }} / {{ t.vehiclePayloadKg }} kg</p>
                <progress [value]="t.totalWeightKg" [max]="t.vehiclePayloadKg"></progress>
                <p data-testid="tour-capacity-meters">
                    {{ t.totalLoadMeters }} / {{ t.vehicleLoadMeters }} load meters
                </p>
                <progress [value]="t.totalLoadMeters" [max]="t.vehicleLoadMeters"></progress>
            </section>

            @if (actionError(); as message) {
                <p data-testid="tour-action-error">{{ message }}</p>
            }

            <section>
                <h2>Stops</h2>
                <table mat-table [dataSource]="t.stops">
                    <ng-container matColumnDef="sequence">
                        <th mat-header-cell *matHeaderCellDef>#</th>
                        <td mat-cell *matCellDef="let s" data-testid="tour-stop-sequence">{{ s.sequence }}</td>
                    </ng-container>
                    <ng-container matColumnDef="orderNumber">
                        <th mat-header-cell *matHeaderCellDef>Order</th>
                        <td mat-cell *matCellDef="let s" data-testid="tour-stop-order">{{ s.orderNumber }}</td>
                    </ng-container>
                    <ng-container matColumnDef="stopType">
                        <th mat-header-cell *matHeaderCellDef>Type</th>
                        <td mat-cell *matCellDef="let s" data-testid="tour-stop-type">{{ s.stopType }}</td>
                    </ng-container>
                    <ng-container matColumnDef="actions">
                        <th mat-header-cell *matHeaderCellDef>Actions</th>
                        <td mat-cell *matCellDef="let s">
                            @if (s.stopType === 'Pickup' && session.can('dispatch.write')) {
                                <button
                                    mat-button
                                    data-testid="tour-remove"
                                    (click)="removeOrder(s.transportOrderId)"
                                >
                                    Remove
                                </button>
                            }
                        </td>
                    </ng-container>
                    <tr mat-header-row *matHeaderRowDef="stopColumns"></tr>
                    <tr mat-row *matRowDef="let row; columns: stopColumns"></tr>
                </table>
            </section>

            @if (session.can('dispatch.write')) {
            <section>
                <h2>Assign an order</h2>
                <!-- Only Draft orders are offered: any other status is refused by the domain,
                     and offering a choice the server will reject is worse than not offering it. -->
                <mat-form-field>
                    <mat-label>Order</mat-label>
                    <mat-select
                        [value]="selectedOrderId()"
                        (valueChange)="selectedOrderId.set($event)"
                        data-testid="tour-assign-select"
                    >
                        @for (order of assignableOrders(); track order.id) {
                            <mat-option [value]="order.id">
                                {{ order.orderNumber }} — {{ order.consignor.name }}
                                ({{ order.cargoWeightKg }} kg)
                            </mat-option>
                        }
                    </mat-select>
                </mat-form-field>
                <button mat-raised-button data-testid="tour-assign" (click)="assign()">Assign</button>
            </section>
            }

            <!-- tourStatus.write, not dispatch.write: a fahrer may run their own tour without
                 being allowed to change what is on it. -->
            @if (session.can('tourStatus.write')) {
                <section>
                    @if (t.status === 'Planned') {
                        <button mat-raised-button data-testid="tour-start" (click)="start()">Start tour</button>
                    }
                    @if (t.status === 'InProgress') {
                        <button mat-raised-button data-testid="tour-complete" (click)="complete()">
                            Complete tour
                        </button>
                    }
                </section>
            }

            <a mat-button routerLink="/tours" data-testid="tour-back">Back to tours</a>
        }
    `,
})
export class TourDetailComponent {
    private readonly service = inject(TourService);
    private readonly orderService = inject(OrderService);
    private readonly route = inject(ActivatedRoute);
    private readonly router = inject(Router);
    // SessionService.ready is what guarantees angular-auth-oidc-client has rehydrated its
    // stored session before the first request goes out; a directly opened /tours/{id} would
    // otherwise send every request without a bearer token. The one checkAuth() behind it runs in
    // the App component.
    protected readonly session = inject(SessionService);

    protected readonly tourId = this.route.snapshot.paramMap.get('id')!;
    protected readonly stopColumns = ['sequence', 'orderNumber', 'stopType', 'actions'];
    protected readonly tour = signal<Tour | null>(null);
    protected readonly draftOrders = signal<Order[]>([]);
    protected readonly selectedOrderId = signal('');
    protected readonly loadError = signal<string | null>(null);
    // Separate from loadError: a refused assignment must not blank the page the way a failed
    // load does. This is where a 409 from the capacity or status rules reaches the user.
    protected readonly actionError = signal<string | null>(null);

    // Orders already on this tour are no longer Draft, but the picker's list is only refreshed
    // alongside the tour, so filter defensively rather than offering a stale choice.
    protected readonly assignableOrders = computed(() => {
        const assigned = new Set(this.tour()?.stops.map((stop) => stop.transportOrderId) ?? []);
        return this.draftOrders().filter((order) => !assigned.has(order.id));
    });

    constructor() {
        this.refresh();
    }

    protected assign(): void {
        const orderId = this.selectedOrderId();
        if (!orderId) {
            this.actionError.set('Choose an order to assign first.');
            return;
        }

        this.actionError.set(null);
        this.run(this.service.assignOrder(this.tourId, orderId), 'The order could not be assigned.');
    }

    protected removeOrder(transportOrderId: string): void {
        this.actionError.set(null);
        this.run(this.service.removeOrder(this.tourId, transportOrderId), 'The order could not be removed.');
    }

    protected start(): void {
        this.actionError.set(null);
        this.run(this.service.start(this.tourId), 'The tour could not be started.');
    }

    protected complete(): void {
        this.actionError.set(null);
        this.run(this.service.complete(this.tourId), 'The tour could not be completed.');
    }

    private run(action: Observable<Tour>, fallback: string): void {
        this.session.ready.pipe(switchMap(() => action)).subscribe({
            next: (tour) => {
                this.tour.set(tour);
                this.selectedOrderId.set('');
                this.loadDraftOrders();
            },
            error: (error: HttpErrorResponse) => this.actionError.set(this.describe(error, fallback)),
        });
    }

    private refresh(): void {
        this.session.ready.pipe(switchMap(() => this.service.getById(this.tourId))).subscribe({
            next: (tour) => {
                this.tour.set(tour);
                this.loadDraftOrders();
            },
            // The load path gets its own wording: "could not be assigned" on a failed getById
            // would be plainly wrong.
            error: (error: HttpErrorResponse) =>
                this.loadError.set(this.describe(error, 'The tour could not be loaded.')),
        });
    }

    // Orders come back sorted by order number ASCENDING, so page 1 is the OLDEST drafts - which
    // in a running installation are the ones nobody has planned for weeks, not the ones a
    // dispatcher is working on today. Fetch the last page instead: one extra request only when
    // there are more drafts than fit on a page, and never more than the API's 100-row cap.
    // Beyond that a searchable picker is needed; a bigger page will not save it.
    private loadDraftOrders(): void {
        const pageSize = 100;

        this.session.ready
            .pipe(
                switchMap(() => this.orderService.list('Draft', pageSize)),
                switchMap((first) => {
                    const lastPage = Math.max(1, Math.ceil(first.totalCount / pageSize));
                    return lastPage === 1 ? of(first) : this.orderService.list('Draft', pageSize, lastPage);
                }),
            )
            .subscribe({
                next: (page) => this.draftOrders.set(page.items),
                error: (error: HttpErrorResponse) =>
                    this.actionError.set(this.describe(error, 'The assignable orders could not be loaded.')),
            });
    }

    // A 403 from the authorization middleware carries no ProblemDetails body at all, while a
    // 403 from TourAccess does - hence a per-call-site fallback rather than one shared string.
    private describe(error: HttpErrorResponse, fallback: string): string {
        const problem = error.error as { title?: string; detail?: string } | null;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.status})`;
    }
}

// src/TransBrain.VueWeb/src/views/TourDetail.vue
<script setup lang="ts">
import axios from 'axios';
import { computed, onMounted, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import { listOrders, type Order } from '../api/orders';
import {
    assignOrderToTour,
    completeTour,
    getTour,
    removeOrderFromTour,
    startTour,
    type Tour,
} from '../api/tours';
import { useAuthStore } from '../stores/auth';

const auth = useAuthStore();
const route = useRoute();
const router = useRouter();

const tourId = route.params.id as string;
const tour = ref<Tour | null>(null);
const draftOrders = ref<Order[]>([]);
const selectedOrderId = ref('');
const loadError = ref<string | null>(null);
// Separate from loadError: a refused assignment must not blank the page the way a failed load
// does. This is where a 409 from the capacity or status rules reaches the user.
const actionError = ref<string | null>(null);

const stopHeaders = [
    { title: '#', key: 'sequence' },
    { title: 'Order', key: 'orderNumber' },
    { title: 'Type', key: 'stopType' },
    { title: 'Actions', key: 'actions', sortable: false },
];

// Orders already on this tour are no longer Draft, but the picker's list is refreshed only
// alongside the tour, so filter defensively rather than offering a stale choice.
const assignableOrders = computed(() => {
    const assigned = new Set(tour.value?.stops.map((stop) => stop.transportOrderId) ?? []);
    return draftOrders.value.filter((order) => !assigned.has(order.id));
});

onMounted(refresh);

async function refresh(): Promise<void> {
    try {
        tour.value = await getTour(tourId);
        await loadDraftOrders();
    } catch (error) {
        // The load path gets its own wording: "could not be assigned" on a failed get would be
        // plainly wrong.
        loadError.value = describe(error, 'The tour could not be loaded.');
    }
}

// Orders come back sorted by order number ASCENDING, so page 1 is the OLDEST drafts - in a
// running installation the ones nobody has planned for weeks, not the ones a dispatcher is
// working on today. Fetch the last page instead: one extra request only when there are more
// drafts than fit on a page. Beyond the API's 100-row cap a searchable picker is needed.
async function loadDraftOrders(): Promise<void> {
    const pageSize = 100;
    try {
        const first = await listOrders('Draft', pageSize);
        const lastPage = Math.max(1, Math.ceil(first.totalCount / pageSize));
        draftOrders.value = lastPage === 1 ? first.items : (await listOrders('Draft', pageSize, lastPage)).items;
    } catch (error) {
        actionError.value = describe(error, 'The assignable orders could not be loaded.');
    }
}

async function assign(): Promise<void> {
    if (!selectedOrderId.value) {
        actionError.value = 'Choose an order to assign first.';
        return;
    }

    await run(() => assignOrderToTour(tourId, selectedOrderId.value), 'The order could not be assigned.');
}

async function remove(transportOrderId: string): Promise<void> {
    await run(() => removeOrderFromTour(tourId, transportOrderId), 'The order could not be removed.');
}

async function start(): Promise<void> {
    await run(() => startTour(tourId), 'The tour could not be started.');
}

async function complete(): Promise<void> {
    await run(() => completeTour(tourId), 'The tour could not be completed.');
}

async function run(action: () => Promise<Tour>, fallback: string): Promise<void> {
    actionError.value = null;
    try {
        tour.value = await action();
        selectedOrderId.value = '';
        await loadDraftOrders();
    } catch (error) {
        actionError.value = describe(error, fallback);
    }
}

// A 403 from the authorization middleware carries no ProblemDetails body at all, while a 403
// from TourAccess does - hence a per-call-site fallback rather than one shared string.
function describe(error: unknown, fallback: string): string {
    if (axios.isAxiosError(error)) {
        const problem = error.response?.data as { title?: string; detail?: string } | undefined;
        const sentence = problem?.detail ?? problem?.title ?? fallback;
        return `${sentence} (HTTP ${error.response?.status ?? 'unknown'})`;
    }
    return fallback;
}
</script>

<template>
    <v-container>
        <h1>Tour</h1>
        <p v-if="loadError" data-testid="tour-detail-error">{{ loadError }}</p>

        <template v-if="tour">
            <!-- tour-detail-* rather than tour-*: the list uses tour-status/tour-date on its
                 cells, and a page-wide locator matching both screens would be ambiguous the
                 moment a test navigated between them. Mirrors the Angular detail page. -->
            <dl>
                <dt>Date</dt>
                <dd data-testid="tour-detail-date">{{ tour.tourDate }}</dd>
                <dt>Vehicle</dt>
                <dd data-testid="tour-detail-vehicle">{{ tour.vehicleLicensePlate }}</dd>
                <dt>Driver</dt>
                <dd data-testid="tour-detail-driver">{{ tour.driverName }}</dd>
                <dt>Status</dt>
                <dd data-testid="tour-detail-status">{{ tour.status }}</dd>
            </dl>

            <!-- The headroom a dispatcher needs before choosing the next order. The API already
                 sends both numbers, so showing them costs nothing extra. -->
            <section>
                <h2>Capacity</h2>
                <p data-testid="tour-capacity-weight">
                    {{ tour.totalWeightKg }} / {{ tour.vehiclePayloadKg }} kg
                </p>
                <progress :value="tour.totalWeightKg" :max="tour.vehiclePayloadKg"></progress>
                <p data-testid="tour-capacity-meters">
                    {{ tour.totalLoadMeters }} / {{ tour.vehicleLoadMeters }} load meters
                </p>
                <progress :value="tour.totalLoadMeters" :max="tour.vehicleLoadMeters"></progress>
            </section>

            <p v-if="actionError" data-testid="tour-action-error">{{ actionError }}</p>

            <section>
                <h2>Stops</h2>
                <v-data-table
                    :headers="stopHeaders"
                    :items="tour.stops"
                    :items-per-page="-1"
                    item-value="sequence"
                    data-testid="tour-stop-table"
                >
                    <template #item.sequence="{ item }">
                        <span data-testid="tour-stop-sequence">{{ item.sequence }}</span>
                    </template>
                    <template #item.orderNumber="{ item }">
                        <span data-testid="tour-stop-order">{{ item.orderNumber }}</span>
                    </template>
                    <template #item.stopType="{ item }">
                        <span data-testid="tour-stop-type">{{ item.stopType }}</span>
                    </template>
                    <template #item.actions="{ item }">
                        <v-btn
                            v-if="item.stopType === 'Pickup' && auth.can('dispatch.write')"
                            data-testid="tour-remove"
                            @click="remove(item.transportOrderId)"
                        >
                            Remove
                        </v-btn>
                    </template>
                </v-data-table>
            </section>

            <section v-if="auth.can('dispatch.write')">
                <h2>Assign an order</h2>
                <!-- Only Draft orders are offered: any other status is refused by the domain,
                     and offering a choice the server will reject is worse than not offering it. -->
                <div>
                    <label for="tour-assign-select">Order</label>
                    <select id="tour-assign-select" v-model="selectedOrderId" data-testid="tour-assign-select">
                        <option value="">-</option>
                        <option v-for="order in assignableOrders" :key="order.id" :value="order.id">
                            {{ order.orderNumber }} — {{ order.consignor.name }} ({{ order.cargoWeightKg }} kg)
                        </option>
                    </select>
                </div>
                <v-btn data-testid="tour-assign" @click="assign">Assign</v-btn>
            </section>

            <!-- tourStatus.write, not dispatch.write: a fahrer may run their own tour without
                 being allowed to change what is on it. -->
            <section v-if="auth.can('tourStatus.write')">
                <!-- Hidden rather than shown-and-refused: a button that can only ever answer 409
                     is noise. Assign and Remove stay visible, matching how the order screens
                     treat Cancel - there the refusal message teaches the rule. -->
                <v-btn v-if="tour.status === 'Planned'" data-testid="tour-start" @click="start">
                    Start tour
                </v-btn>
                <v-btn v-if="tour.status === 'InProgress'" data-testid="tour-complete" @click="complete">
                    Complete tour
                </v-btn>
            </section>

            <v-btn data-testid="tour-back" @click="router.push('/tours')">Back to tours</v-btn>
        </template>
    </v-container>
</template>
